### ISSUE TITLE
AWS transcribe_to_docx.py failure as a result of missing Speaker and Channel mode labels

### ISSUE THREAD

**Issue by pcberg** [indiana-university/automated-transcription-service#25]
We received a file in (language) Kinyarwanda for which AWS transcribe outputs a file that is missing both speaker (speaker_labels) and channel (channel_labels) labels. Our (transcribe_to_docx.py) process fails with the following error:

`FAIL: No speaker or channel information found in JSON file.`

That is because our generate_document function checks for presence of either speaker or channel mode (ref: https://github.com/indiana-university/automated-transcription-service/blob/340575a5c6931d23c980a4c4ec41959766097bf8/aws/src/lambda/transcribe_to_docx.py#L930).

Furthermore we ran this through the stock transcribe_to_docx.py and it fails with this error:

`Traceback (most recent call last):
  File "ts-to-word.py", line 1857, in <module>
    generate_document()
  File "ts-to-word.py", line 1827, in generate_document
    speech_segments, summaries_detected = create_turn_by_turn_segments(json_data, cli_args)
  File "ts-to-word.py", line 1491, in create_turn_by_turn_segments
    for segment in data["results"]["speaker_labels"]["segments"]:
KeyError: 'speaker_labels'`

That is because the stock version doesn't have our if-statement but subsequently fails on processing logic when trying to loop over speaker labels (ref: https://github.com/aws-samples/amazon-transcribe-output-word-document/blob/d91b6c58ffb2e8919f58cabd66019397c747dc35/python/ts-to-word.py#L1491). This error would also occur in our transcribe_to_docx.py if we didn't have the if-statement, the core loops are similar on the two codes.

**Comment by pcberg** [comment]
Please re-test this, it looks like the if-condition for command line execution was updated but not lambda execution.

**Comment by pcberg** [comment]
Additional PR for this: https://github.com/indiana-university/automated-transcription-service/pull/40
